### ISSUE TITLE
Research best output option for Metric Beats

### ISSUE THREAD

**Issue by MyBucketIsFull** [hexoxide/O2-Balancer2#1]

**Comment by Dantali0n** [comment]
I consider this done. Or solution is the basic ELK stack with metricbeats. 

![relationship-between-filebeat-and-logstash](https://user-images.githubusercontent.com/5026295/50214716-da9a1280-0378-11e9-9bad-3360721e0c5f.png)

Please USE IMAGE IN TDR @MyBucketIsFull
